production:
  adapter: postgresql
  encoding: unicode
  database: portal_production
  pool: 5
  username: portal_std
  password: ALT/chi!
  host: 127.0.0.1

development:
  adapter: postgresql
  encoding: unicode
  database: portal_development
  pool: 100
  username: portal_std
  password: ALT/chi!
  host: 127.0.0.1
  reconnect: true

test:
  adapter: postgresql
  encoding: unicode
  database: portal_test
  pool: 100
  username: portal_std
  password:
  host: 127.0.0.1
  reconnect: true
