development:
  adapter: postgresql
  encoding: unicode
  database: portal_development
  pool: 5
  username: shanesv
  password: nmrp2013
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: portal_test
  pool: 5
  username: shanesv
  password: nmrp2013
  host: 127.0.0.1
