development:
  adapter: postgresql
  encoding: unicode
  database: portal_development
  pool: 5
  username: portal_std
  password:
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: portal_test
  pool: 5
  username: portal_std
  password:
  host: 127.0.0.1
