module IfiltersHelper
  def get_filtered_row(f, row)
    retval = []
    
    t = row.first() #ignore everything but first
    matches = /#{f.regex}/.match(t)

    #if regex finds matches, populate 
    if matches != nil
      matches.captures.each do |mtext|
        retval << mtext
      end
    end
    
    return retval
  end
  
  #Returns a autogenerated list of colnames, based on column number
  # i.e. [1,2,3...]
  def get_filtered_colnames(row)
    return (1..row.count).to_a
  end
  
  def get_ifilter_headers(ifilter)
    retval = []
    begin
      if ifilter.stuffing_headers != nil
        retval = ifilter.stuffing_headers
      end
    rescue
      retval = []
    end
    
    return retval
  end
end
