#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'

#ENV['RAILS_ENV'] = ARGV.pop

Delayed::Command.new(ARGV).daemonize
